//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webapiforprac
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaveDetail
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> Continent { get; set; }
        public Nullable<int> Country { get; set; }
        public Nullable<int> City { get; set; }
        public Nullable<bool> Remember { get; set; }
    }
}
